name: CI

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
        
      - name: Build with Ant
        run: ant -f build-auto.xml dist
        
      - name: Move builds to apporiate artifact folders
        run: cd dist;rm -R -- */;cd ..;mkdir -p dist/{buildWin32,buildLinux,buildMacOS};mv dist/*windows* dist/buildWin32/;mv dist/*linux* dist/buildLinux/;mv dist/*macosx* dist/buildMacOS/;
        continue-on-error: true
      
      - name: Publishing Win32 builds
        uses: actions/upload-artifact@v2
        with:
          name: Win32 builds
          path: dist/buildWin32
      
      - name: Publishing Linux builds
        uses: actions/upload-artifact@v2
        with:
          name: Linux builds
          path: dist/buildLinux

      - name: Publishing MacOS builds
        uses: actions/upload-artifact@v2
        with:
          name: Mac OS builds
          path: dist/buildMacOS
          
      - name: Release tagged builds
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
            gpl.txt
