name: CI

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
        
      - name: Build with Ant
        run: ant -f build-auto.xml dist
        
      - name: Move builds to apporiate artifact folders
        run: |
          # Remove all unnecessary build folders since we will only release builds with archived with 7zip
          cd dist
          rm -R -- */
          cd ..
          # Make directories for artifact releases and move all of builds to their respective folders
          mkdir -p dist/{buildWin32/x86,buildWin32/amd64,buildLinux/x86,buildLinux/amd64,buildMacOS}
          mv dist/*linux-amd64* dist/buildLinux/amd64/
          mv dist/*linux-x86* dist/buildLinux/x86/
          mv dist/*windows-x86* dist/buildWin32/x86/
          mv dist/*windows-amd64* dist/buildWin32/amd64/
          mv dist/*macosx* dist/buildMacOS/
     
      - name: Publishing Win32 x86 build
        uses: actions/upload-artifact@v2
        with:
          name: Win32 x86 build
          path: dist/buildWin32/x86

      - name: Publishing Win32 amd64 build
        uses: actions/upload-artifact@v2
        with:
          name: Win32 amd64 build
          path: dist/buildWin32/amd64
      
      - name: Publishing Linux x86 build
        uses: actions/upload-artifact@v2
        with:
          name: Linux x86 build
          path: dist/buildLinux/x86

      - name: Publishing Linux amd64 build
        uses: actions/upload-artifact@v2
        with:
          name: Linux amd64 build
          path: dist/buildLinux/amd64

      - name: Publishing MacOS build
        uses: actions/upload-artifact@v2
        with:
          name: Mac OS build
          path: dist/buildMacOS
          
      - name: Release tagged builds
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            dist/buildLinux/x86/*.7z
            dist/buildLinux/amd64/*.7z
            dist/buildMacOS/*.7z
            dist/buildWin32/x86/*.7z
            dist/buildWin32/amd64/*.7z
