name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
        
      - name: Build with Ant
        run: ant -f build-auto.xml dist
        
      - name: Move builds to apporiate artifact folders
        run: cd dist;ls;rm -R -- */;cd ..;mkdir -p dist/{win32,linux,macOS};mv dist/*windows* dist/win32/ 2>/dev/null;mv dist/*linux* dist/linux/ 2>/dev/null;mv dist/*macosx* dist/macOS/ 2>/dev/null;
        continue-on-error: true
      - uses: actions/upload-artifact@v2
        with:
          name: Win32 builds
          path: dist/win32

      - uses: actions/upload-artifact@v2
        with:
          name: Linux builds
          path: dist/linux

      - uses: actions/upload-artifact@v2
        with:
          name: Mac OS builds
          path: dist/macOS